export const jogadoresNaUCL = [
  {
    info: [
      {
        id: 1,
        nome: "Cristiano Ronaldo",
        nacionalidade: "Portugal",
        posicao: "Atacante",
        idade: 37,
        jogos: 187,
        gols: 141,
        times: 3,
        aposentado: false,
        posts: [
          {
            userId: 1,
            id: 1,
            title: "Líder do ranking histórico da Uefa Champions League",
            body: "Cristiano Ronaldo é, sem dúvidas, o maior jogador da história da Liga dos Campeões.",
          },
          {
            userID: 1,
            id: 2,
            title: "Por isso ele é o maior",
            body: "Grandes jogadores são capazes de mudar a história de uma partida, e nenhum deles teve mais êxito, por tantas vezes e com tanta vontade do que Cristiano Ronaldo, seus cinco títulos de Liga dos Campeões comprovam isso. Ele é o jogador com mais jogos disputados e com mais gols na UCL.",
          },
        ],
      },
      {
        id: 2,
        nome: "Lionel Messi",
        nacionalidade: "Argentina",
        posicao: "Atacante",
        idade: 34,
        jogos: 156,
        gols: 125,
        times: 2,
        aposentado: false,
        posts: [
          {
            userID: 2,
            id: 3,
            title: "Segundo colocado no ranking",
            body: "Os feitos de Messi em títulos da Liga dos Campeões (3) e gols (125) são assustadores, mas inferiores ao homem que está no topo. ",
          },
          {
            userID: 2,
            id: 4,
            title: "Merecia ser o primeiro?",
            body: "Desde que estreou na competição com 17 anos, Messi fez coisas com a bola que são incomparáveis.Sua atuação avassaladora de quatro gols contra o Arsenal em 2010, além do corte seco em Jerome Boateng seguido de uma cavadinha sob Manuel Neuer, o momento esportivo mais tuitado de 2015 e o gol da temporada na Europa.",
          },
        ],
      },
      {
        id: 3,
        nome: "Sergio Ramos",
        nacionalidade: "Espanha",
        posicao: "Zagueiro",
        idade: 36,
        jogos: 129,
        gols: 15,
        times: 1,
        aposentado: false,
        posts: [
          {
            userID: 3,
            id: 5,
            title: "Terceiro colocado no ranking",
            body: "Muitos jogadores foram melhores que Sergio Ramos na Liga dos Campeões, mas poucos tão relevantes. O ex-capitão do Real Madrid é a personificação do time que venceu a competição quatro vezes entre 2014 e 2018.",
          },
          {
            userID: 3,
            id: 6,
            title: "Por que um zagueiro em terceiro no ranking?",
            body: "Ele é muito decisivo, o famoso jogador de jogo grande. Sergio Ramos marcou duas vezes de cabeça em quatro minutos na semifinal de 2014 destruindo o Bayern. Ele empatou nos acréscimos do segundo tempo na final daquele ano, forçando na marra a prorrogação que o Real venceu por 4 a 1, levantando a La Decima. E foi Sergio Ramos que marcou o único gol na final de 2016, quando o Real derrotou o Atletico na disputa por pênaltis.",
          },
        ],
      },
      {
        id: 4,
        nome: "Andrés Iniesta",
        nacionalidade: "Espanha",
        posicao: "Meia",
        idade: 37,
        jogos: 132,
        gols: 11,
        times: 1,
        aposentado: false,
        posts: [
          {
            userID: 4,
            id: 7,
            title: "Quarto colocado no ranking",
            body: "É impossível falar de Andrés Iniesta sem imediatamente lembrar de seu gol da vitória contra o Chelsea, nos acréscimos do segundo tempo, pela semifinal de 2008/09 em Stamford Bridge. O passe de Messi, a finalização de três dedos, a bola indo no ângulo, a comemoração sem camisa, sua camiseta térmica amarela.",
          },
          {
            userID: 4,
            id: 8,
            title: "Um jogador essencial",
            body: "Mas focar apenas em um momento específico seria rebaixar a carreira de um dos melhores jogadores de um dos mais talentosos times da história. Ele não marcou muitos gols nem foi responsável por muitas assistências, mas isto não importava. Era a forma como jogava, o ritmo que dava ao jogo. Se inteligência em campo fosse determinada por QI, Iniesta teria o equivalente de futebol de um Stephen Hawking.",
          },
        ],
      },
      {
        id: 5,
        nome: "Raúl González",
        nacionalidade: "Espanha",
        posicao: "Atacante",
        idade: 44,
        jogos: 142,
        gols: 71,
        times: 2,
        aposentado: true,
        posts: [
          {
            userID: 5,
            id: 9,
            title: "Quinto colocado no ranking",
            body: "É difícil se lembrar agora, mas houve um tempo antes de Lionel Messi e Cristiano Ronaldo desembarcarem do espaço sideral e arruinarem o futebol para todos que já jogaram contra eles. E naquela época, era Raul quem elevava o nível com atuações espetaculares.",
          },
          {
            userID: 5,
            id: 10,
            title: "O jogador espanhol mais importante da história",
            body: "Descrito por Pep Guardiola como “o jogador espanhol mais importante da história”, ele marcou 71 gols em 142 partidas de Liga dos Campeões. Raul era o jogador que você fingia ser no recreio, com uma camisa com o seu nome nas costas.",
          },
        ],
      },
      {
        id: 6,
        nome: "Paolo Maldini",
        nacionalidade: "Itália",
        posicao: "Zagueiro",
        idade: 53,
        jogos: 139,
        gols: 3,
        times: 1,
        aposentado: true,
        posts: [
          {
            userID: 6,
            id: 11,
            title: "Sexto colocado no ranking",
            body: "Maldini já havia vencido a antiga Copa dos Clubes Campeões Europeus duas vezes antes de ser renomeada em 1992, o que me parece apropriado quando se fala do zagueiro mais atemporal da Liga dos Campeões",
          },
          {
            userID: 6,
            id: 12,
            title: "Il Capitano",
            body: "Nos 15 anos seguintes, ele jogou em mais seis finais pelo AC Milan, alternando de posição entre lateral esquerdo e zagueiro central. Das seis, ele venceu três, duas como capitão e foi eleito o melhor em campo contra a Juventus em 2003, na única final da história a terminar em 0 a 0. Ainda por cima, fez tudo isso parecendo ser ator de um filme de Federico Fellini, lendo o jornal em alguma praça italiana tranquila, enquanto todo mundo suava ao seu redor. ",
          },
        ],
      },
      {
        id: 7,
        nome: "Iker Casillas",
        nacionalidade: "Espanha",
        posicao: "Goleiro",
        idade: 40,
        jogos: 181,
        gols: 0,
        times: 2,
        aposentado: true,
        posts: [
          {
            userID: 7,
            id: 13,
            title: "Sétimo colocado no ranking",
            body: "O goleiro melhor colocado nesta lista não poderia ser outro. Até pouco tempo atrás, Casillas era o recordista de partidas jogadas na história da Liga dos Campeões, embora isto não deva surpreender, dada a sua longevidade sempre no auge.",
          },
          {
            userID: 7,
            id: 14,
            title: "Um dos maiores goleiros de todos os tempos",
            body: "Ele se tornou o goleiro titular mais jovem e vencer uma final de Liga dos Campeões, após ser titular na vitória do Real Madrid por 3 a 0 contra o Valencia em 2000, com apenas 19 anos. Quatorze anos mais tarde, ele era o capitão do seu time na conquista da La Decima. Ele foi nomeado o Melhor Goleiro do Mundo em todos os anos desde 2008 até 2012.",
          },
        ],
      },
      {
        id: 8,
        nome: "Xavi Hernández",
        nacionalidade: "Espanha",
        posicao: "Meia",
        idade: 42,
        jogos: 157,
        gols: 12,
        times: 1,
        aposentado: true,
        posts: [
          {
            userID: 8,
            id: 15,
            title: "Oitavo colocado no ranking",
            body: " 'Eu tenho certeza que já vi ele errando um passe'. Sir Alex Ferguson estava quase que brincando quando disse esta frase. Depois que Xavi deixou o time do Manchester United atordoado na final da Liga dos Campeões de 2011 em Wembley, pode-se imaginar que as mesmas palavras foram ditas novamente, mas com mais irritação.",
          },
          {
            userID: 8,
            id: 16,
            title: "Maestro",
            body: "Xavi era conhecido como o “Mestre de Marionetes” naquele trio memorável de meio-campistas, ao lado de Sergio Busquets e Andres Iniesta. Ele não apenas controlava o jogo, encontrando espaço onde ninguém via para receber a bola, mas também conseguia confundir os adversários com suas tomadas de decisões. Muitas das aulas de Lionel Messi vieram contra defensores cujos cérebros foram embaralhados por Xavi. Se aposentar com três títulos da Liga dos Campeões na bagagem, garante que Xavi será sempre lembrado por frustrar Ferguson e vários outros de diferentes maneiras.",
          },
        ],
      },
      {
        id: 9,
        nome: "Samuel Eto'o",
        nacionalidade: "Camarões",
        posicao: "Atacante",
        idade: 41,
        jogos: 82,
        gols: 33,
        times: 5,
        aposentado: true,
        posts: [
          {
            userID: 9,
            id: 17,
            title: "Nono colocado no ranking",
            body: "Eto'o deve ter se sentido muito convencido após vencer a Liga dos Campeões com a Inter de Milão em 2010. Um ano antes, ele havia sido dispensado do Barcelona por Pep Guardiola, apesar de desempenhar um papel essencial para o time que era o atual campeão – marcando um gol na final contra o Manchester United – apenas algumas semanas antes.",
          },
          {
            userID: 9,
            id: 18,
            title: "Um dos maiores jogadores africanos da história",
            body: "O triunfo de Eto'o com a Inter marcava seu terceiro título na competição, todos conquistados em um espaço de cinco temporadas. Seu primeiro veio com o Barcelona em 2006, marcando o gol de empate na final contra o Arsenal e sofrendo falta de Jens Lehmann, expulso, deixando a equipe inglesa com 10 jogadores. Outros atacantes marcaram mais gols na competição, mas poucos foram tão impactantes quanto Eto'o.",
          },
        ],
      },
      {
        id: 10,
        nome: "Zinedine Zidane",
        nacionalidade: "França",
        posicao: "Meia",
        idade: 49,
        jogos: 82,
        gols: 14,
        times: 2,
        aposentado: true,
        posts: [
          {
            userID: 10,
            id: 19,
            title: "Décimo colocado no ranking",
            body: "Um título de Liga dos Campeões talvez seja decepcionante para um jogador tão lendário quanto Zidane. No entanto, que grande título foi este. A final de 2002 sempre será lembrada por uma coisa apenas: o golaço de Zizou, o maior gol da história da Liga dos Campeões. Com o cruzamento de Roberto Carlos vindo de muito alto, o francês girou o corpo e arrematou um voleio perfeito – com o pé ruim – no ângulo.",
          },
          {
            userID: 10,
            id: 20,
            title: "Jogava de terno",
            body: "Além de produzir momentos de pura genialidade, ele era reverenciado por seus companheiros pela sua habilidade em controlar o jogo. “Quando Zidane pisava em campo, os outros 10 do time, de repente, jogavam melhor,” Zlatan Ibrahimovic disse sobre o incrível francês. Seu sucesso como treinador nos faz esquecer do jogador que Zidane era. Um meio campista clássico, completo.",
          },
        ],
      },
    ],
  },
];
