export const jogadoresNaUCL = [
  {
    info: [
      {
        id: 1,
        nome: "Cristiano Ronaldo",
        nacionalidade: "Portugal",
        posicao: "Atacante",
        idade: 37,
        jogos: 187,
        gols: 141,
        times: 3,
        aposentado: false,
      },
      {
        id: 2,
        nome: "Lionel Messi",
        nacionalidade: "Argentina",
        posicao: "Atacante",
        idade: 34,
        jogos: 156,
        gols: 125,
        times: 2,
        aposentado: false,
      },
      {
        id: 3,
        nome: "Sergio Ramos",
        nacionalidade: "Espanha",
        posicao: "Zagueiro",
        idade: 36,
        jogos: 129,
        gols: 15,
        times: 1,
        aposentado: false,
      },
      {
        id: 4,
        nome: "Andrés Iniesta",
        nacionalidade: "Espanha",
        posicao: "Meia",
        idade: 37,
        jogos: 132,
        gols: 11,
        times: 1,
        aposentado: false,
      },
      {
        id: 5,
        nome: "Raúl González",
        nacionalidade: "Espanha",
        posicao: "Atacante",
        idade: 44,
        jogos: 144,
        gols: 71,
        times: 2,
        aposentado: true,
      },
      {
        id: 6,
        nome: "Paolo Maldini",
        nacionalidade: "Itália",
        posicao: "Zagueiro",
        idade: 53,
        jogos: 139,
        gols: 3,
        times: 1,
        aposentado: true,
      },
      {
        id: 7,
        nome: "Iker Casillas",
        nacionalidade: "Espanha",
        posicao: "Goleiro",
        idade: 40,
        jogos: 181,
        gols: 0,
        times: 2,
        aposentado: true,
      },
      {
        id: 8,
        nome: "Xavi Hernández",
        nacionalidade: "Espanha",
        posicao: "Meia",
        idade: 42,
        jogos: 157,
        gols: 12,
        times: 1,
        aposentado: true,
      },
      {
        id: 9,
        nome: "Samuel Eto'o",
        nacionalidade: "Camarões",
        posicao: "Atacante",
        idade: 41,
        jogos: 82,
        gols: 33,
        times: 5,
        aposentado: true,
      },
      {
        id: 10,
        nome: "Zinedine Zidane",
        nacionalidade: "França",
        posicao: "Meia",
        idade: 49,
        jogos: 82,
        gols: 14,
        times: 2,
        aposentado: true,
      },
    ],
  },
];
