POST http://localhost:3003/user/create 
Content-Type: application/json 

{
    "name": "Marcos",
    "email": "marcos@email.com",
    "password": "1223145153"
}


###
GET http://localhost:3003/user/get


###
POST http://localhost:3003/movie/create 
Content-Type: application/json 

{
    "title": "A Mordida do Banguelo",
    "description": "Uma comédia de cair o queixo",
    "duration_in_minutes": 100,
    "year_of_release": 2022 
}


###
GET http://localhost:3003/movie/get
